name: UnitTest

on:
  push:
    branches:
      - "**" # matches every branch
    tags:
      - "v**"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
        id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools && python -m pip install -r requirements.txt

      - name: Configure AWS Credentials for mock test
        run: aws configure set aws_access_key_id "123" && aws configure set aws_secret_access_key "123" && aws configure set region "ap-eastnorth-1" && aws configure set output "text"

      - name: Run test
        run: pytest

  package:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: ./*
          retention-days: 1